# Pipeline for building package documentation

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  displayName: "Use Python 3.10"
  inputs:
    versionSpec: '3.10'
    # architecture: 'x64'
  
- script: |
    python -m pip install --upgrade pip
    pip install pipx
    pipx install poetry
    poetry install --with doc,dev
  displayName: "Install Python Requirements"

- script: |
    cd docs
    sphinx-apidoc -o . ../src/trafficgen
    make html
  displayName: "Make docs"

- script: |
    poetry build
    mkdir ./docs/build/html/dist
    mv ./dist/*.tar.gz ./docs/build/html/dist/
  displayName: "Build and copy package"

- task: PublishBuildArtifacts@1
  displayName: "Publish HTML"
  inputs:
    pathToPublish: './docs/build/html'
    artifactName: 'docs_html'