name: Build Package

on: workflow_call

jobs:
  build:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Build source distribution and wheel
        run: uv build
      - name: Run twine check
        run: uvx twine check --strict dist/*
      - uses: actions/upload-artifact@v4
        with:
          path: |
            dist/*.tar.gz
            dist/*.whl
