name: Merge into release

on:
  workflow_call:
    secrets:
      RELEASE_TOKEN:
        required: true

jobs:
  merge_into_release:
    name: Merge ${{ github.event.ref }} -> release branch
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch the whole history to prevent unrelated history errors
          fetch-depth: 0
          # The branch you want to checkout (usually equal to `branchtomerge`)
          # ref: ${{ github.event.ref }}
      - uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          target_branch: release
          github_token: ${{ secrets.RELEASE_TOKEN }}
