name: Requirements Files

on: workflow_call

jobs:
  requirements:
    name: Create requirements files from poetry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # cache pip dependencies
      - name: Create requirements files from poetry.lock file
        run: |
          pip install poetry
          poetry lock
          poetry export -o requirements.txt --without-hashes --format requirements.txt
          poetry export -o requirements-dev.txt --without-hashes --format requirements.txt --with dev
          poetry export -o requirements-docs.txt --without-hashes --format requirements.txt --with docs
      - name: Upload requirements files as artifact
        uses: actions/upload-artifact@v3
        with:
          name: requirements-files
          path: |
            poetry.lock
            requirements.txt
            requirements-dev.txt
            requirements-docs.txt
      - name: Delete poetry.lock file
        run: |
          rm -f poetry.lock
