name: Unit Tests

on: workflow_call

jobs:
  test:
    name: Test (Python ${{ matrix.python }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ['3.11', '3.12', '3.13', '3.14']
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'
      - name: Install the project
        run: uv sync -p ${{ matrix.python }} -U --no-dev
      - name: Run pytest
        run: >
          uv run --with pytest --with pytest-cov
          pytest --cov
