name: Nightly Build
run-name: Nightly Build (by @${{ github.actor }})

on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  test:
    uses: ./.github/workflows/_test.yml
  test_future:
    uses: ./.github/workflows/_test_future.yml
  build_package:
    needs:
      - test
    uses: ./.github/workflows/_build_package.yml
  build_and_publish_documentation:
    needs:
      - build_package
    uses: ./.github/workflows/_build_and_publish_documentation.yml
