name: Nightly Build
run-name: Nightly Build (by @${{ github.actor }})

on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  requirements_files:
    uses: ./.github/workflows/_requirements_files.yml
  code_quality:
    needs: requirements_files
    uses: ./.github/workflows/_code_quality.yml
  test:
    needs: requirements_files
    uses: ./.github/workflows/_test.yml
  test_future:
    needs: requirements_files
    uses: ./.github/workflows/_test_future.yml
  build_package:
    needs:
      - code_quality
      - test
    uses: ./.github/workflows/_build_package.yml
  build_and_publish_documentation:
    needs:
      - build_package
    uses: ./.github/workflows/_build_and_publish_documentation.yml
