name: Publish Release
run-name: Publish Release ${{ github.event.ref }} created by @${{ github.actor }}

on:
  push:
    tags:
      - v*

jobs:
  # requirements_files:
  #   uses: ./.github/workflows/_requirements_files.yml
  # build_package:
  #   needs:
  #     - requirements_files
  #   uses: ./.github/workflows/_build_package.yml
  # publish_package:
  #   needs:
  #     - build_package
  #   uses: ./.github/workflows/_publish_package.yml
  #   secrets:
  #     PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
  merge_into_release:
    uses: ./.github/workflows/_merge_into_release.yml
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
